version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "192.168.1.214:3002:3000"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://3.227.197.24:5002
      - REACT_APP_PASSWORD=${REACT_APP_PASSWORD}
    volumes:
      - app_data:/app/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "192.168.1.214:5002:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
      - HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongodb:27017/language-storygen
    depends_on:
      - mongodb
    volumes:
      - app_data:/app/data

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "192.168.1.214:27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  app_data:
    driver: local
  mongodb_data:
    driver: local
