version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3002:3000"
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - app_data:/app/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5002:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
      - HOST=0.0.0.0
    volumes:
      - app_data:/app/data

volumes:
  app_data:
    driver: local
